name: parches

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Fix paths in all HTML files
        run: |
          for file in ./dist/*.html; do
            sed -i 's|href="/|href="/parches/|g' "$file"
            sed -i 's|src="/|src="/parches/|g' "$file"
            sed -i 's|src="/especialidades/|src="/parches/especialidades/|g' "$file"
          done
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Cambia esto si tu carpeta de salida es diferente
